//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitadelsSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CitadelsSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_01 {
            get {
                object obj = ResourceManager.GetObject("char_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_02 {
            get {
                object obj = ResourceManager.GetObject("char_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_03 {
            get {
                object obj = ResourceManager.GetObject("char_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_04 {
            get {
                object obj = ResourceManager.GetObject("char_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_05 {
            get {
                object obj = ResourceManager.GetObject("char_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_06 {
            get {
                object obj = ResourceManager.GetObject("char_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_07 {
            get {
                object obj = ResourceManager.GetObject("char_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_08 {
            get {
                object obj = ResourceManager.GetObject("char_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_09 {
            get {
                object obj = ResourceManager.GetObject("char_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_10 {
            get {
                object obj = ResourceManager.GetObject("char_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_11 {
            get {
                object obj = ResourceManager.GetObject("char_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_12 {
            get {
                object obj = ResourceManager.GetObject("char_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_13 {
            get {
                object obj = ResourceManager.GetObject("char_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_14 {
            get {
                object obj = ResourceManager.GetObject("char_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_15 {
            get {
                object obj = ResourceManager.GetObject("char_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_16 {
            get {
                object obj = ResourceManager.GetObject("char_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_17 {
            get {
                object obj = ResourceManager.GetObject("char_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap char_18 {
            get {
                object obj = ResourceManager.GetObject("char_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9,王后,White,AtBegining,Queen_None,char_09,若坐在國王旁邊可獲得『3枚金幣』，不論國王死活;
        ///1,女巫,White,AtBegining,Witch_Char,char_10,公布你想要迷惑的角色並結束這回合;
        ///2,稅務官,White,AtBegining,TaxCollector_None,char_11,若有玩家蓋建築物，他的回合結束時必須給你1枚金幣;
        ///3,巫師,White,ByWill,Wizard_Player,char_12,觀看一個玩家的手牌並且拿走一張。可底免建築費用或當手牌使用。可蓋重複的建築物;
        ///4,皇帝,Yellow,AtBegining,Emperor_Player,char_13,可將皇冠卡交給指定玩家;
        ///5,修道院長,Blue,AtBegining,Abbot_None,char_14,擁有最多金幣的玩家要給你1枚金幣;
        ///6,煉金術師,White,AtBegining,Alchemist_None,char_15,拿回此回合蓋建築物所花費的金幣;
        ///7,航海家,White,AtBegining,Navigator_None,char [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharExt {
            get {
                return ResourceManager.GetString("CharExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,刺客,White,AtBegining,Assassin_Char,char_01,選擇一個角色並將他殺死，若暗殺成功則該角色此回合無法執行任何動作;
        ///2,盜賊,White,AtBegining,Thief_Char,char_02,選擇一個角色並且洗劫，輪到這個角色時，拿走他所有的金幣;
        ///3,魔法師,White,ByWill,Magician_Player,char_03,你可以和任一個玩家交換手牌，或者棄掉一定數量手牌後從牌堆中拿取相同張數;
        ///4,國王,Yellow,AtBegining,King_None,char_04,輪到你行動時可以獲得皇冠，下回合將從你開始選取角色;
        ///5,主教,Blue,AtBegining,Bishop_None,char_05,領主無法攻擊/拆除你的建築物;
        ///6,商人,Green,AtBegining,Merchant_None,char_06,輪到你行動時可額外獲得一枚金幣;
        ///7,建築師,White,AtBegining,Architect_None,char_07,行動時可以無條件多抽兩張建築卡，且一回合內最多可蓋3個建築;
        ///8,領主,Red,ByWil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharStd {
            get {
                return ResourceManager.GetString("CharStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Citadels {
            get {
                object obj = ResourceManager.GetObject("Citadels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Coin {
            get {
                object obj = ResourceManager.GetObject("Coin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crown {
            get {
                object obj = ResourceManager.GetObject("Crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HandCard {
            get {
                object obj = ResourceManager.GetObject("HandCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p01 {
            get {
                object obj = ResourceManager.GetObject("p01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p02 {
            get {
                object obj = ResourceManager.GetObject("p02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p03 {
            get {
                object obj = ResourceManager.GetObject("p03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p04 {
            get {
                object obj = ResourceManager.GetObject("p04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p05 {
            get {
                object obj = ResourceManager.GetObject("p05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p06 {
            get {
                object obj = ResourceManager.GetObject("p06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p07 {
            get {
                object obj = ResourceManager.GetObject("p07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p08 {
            get {
                object obj = ResourceManager.GetObject("p08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p09 {
            get {
                object obj = ResourceManager.GetObject("p09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p10 {
            get {
                object obj = ResourceManager.GetObject("p10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p11 {
            get {
                object obj = ResourceManager.GetObject("p11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巨龍門,6,Purple,p01,1,FALSE,ExtraPointPlusTwo,國家已經有超過1000年沒見過了。雖然建築費用是六枚金幣，遊戲結束時可以8分計算;
        ///魔法學校,6,Purple,p02,1,FALSE,TaxAnyColor_Gold,計算金幣稅收時，魔法學校可視為任何顏色的建築。如果你是國王、主教、商人、領主 ,稅收可以+1;
        ///實驗室,5,Purple,p03,1,TRUE,AbandomChange,在你的回合當中，可以從手牌中棄掉一張建築卡並換取一枚金幣。此特殊能力每回合只能使用一次;
        ///圖書館,6,Purple,p04,1,FALSE,DrawTwoCard,如果你在回合開始時選擇抽牌，可以保留兩張建築卡。(不需2選1);
        ///鬼城,2,Purple,p05,1,FALSE,ChangeBuildingColor_Silver,計算最後分數時，此卡片可當作任一個顏色的建築物。但如果在遊戲最後一個回合才建成鬼城，不能使用該能力;
        ///長城,6,Purple,p06,1,FALSE,ExtraDestructionPoint,『領主』拆除你的建築物要多1枚金幣;
        ///墓地,5,Purpl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PurpleCard {
            get {
                return ResourceManager.GetString("PurpleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rainbow {
            get {
                object obj = ResourceManager.GetObject("Rainbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s01 {
            get {
                object obj = ResourceManager.GetObject("s01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s02 {
            get {
                object obj = ResourceManager.GetObject("s02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s03 {
            get {
                object obj = ResourceManager.GetObject("s03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s04 {
            get {
                object obj = ResourceManager.GetObject("s04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s05 {
            get {
                object obj = ResourceManager.GetObject("s05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s06 {
            get {
                object obj = ResourceManager.GetObject("s06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s07 {
            get {
                object obj = ResourceManager.GetObject("s07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s08 {
            get {
                object obj = ResourceManager.GetObject("s08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s09 {
            get {
                object obj = ResourceManager.GetObject("s09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s10 {
            get {
                object obj = ResourceManager.GetObject("s10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s11 {
            get {
                object obj = ResourceManager.GetObject("s11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s12 {
            get {
                object obj = ResourceManager.GetObject("s12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s13 {
            get {
                object obj = ResourceManager.GetObject("s13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s14 {
            get {
                object obj = ResourceManager.GetObject("s14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s15 {
            get {
                object obj = ResourceManager.GetObject("s15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s16 {
            get {
                object obj = ResourceManager.GetObject("s16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s17 {
            get {
                object obj = ResourceManager.GetObject("s17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 莊園,3,Yellow,s01,5;
        ///城堡,4,Yellow,s02,4;
        ///戰場,3,Red,s03,3;
        ///監獄,2,Red,s04,3;
        ///瞭望塔,1,Red,s05,3;
        ///教堂,2,Blue,s06,3;
        ///神殿,1,Blue,s07,3;
        ///修道院,3,Blue,s08,3;
        ///大教堂,5,Blue,s09,2;
        ///要塞,5,Red,s10,2;
        ///宮殿,5,Yellow,s11,3;
        ///酒館,1,Green,s12,5;
        ///商棧,2,Green,s13,3;
        ///市政廳,5,Green,s14,2;
        ///港口,4,Green,s15,3;
        ///集市,2,Green,s16,2;
        ///船塢,3,Green,s17,3;.
        /// </summary>
        internal static string SimpleCard {
            get {
                return ResourceManager.GetString("SimpleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie_Fan2,有什麼好抗議的，抗議無效~,這裡到底是Board-Game會還是整人會啊！,我不是針對你啊，我是說在座的各位……都是垃圾,你就像豆腐(豆腐)　豆腐(豆腐),生炒牛肉飯上面第二個是什麼，不准想，快點說！,我準備好了~~,正所謂，最大的敵人就是自己…,坐在這裡打Board-Game，會贏也是很合理的,電腦分析35%是King，65%是Queen,我才是Board-Game的真正傳人！而你們倆個只不過是騙子！,Very Good !!!就憑你這對充滿鬥志的眼神我肯定你是有潛力的，馬上付錢，馬上拜師,X，我國寶捏！,Don&apos;t give up，never give up！,你名義老爸在你後面他非常火,想做好人？行！去跟法官說
        ///Movie_Fan,對手實在太弱了,Hope is a good thing,You are terminated,There is no spoon,You jump . I jump,好～（壓塊玉牌在桌上）我就跟你賭命,一將功成萬骨枯,對不起，還是給零分！收工,看來，這位Board-Game奇才，就是我!!!,我上等威風，顯現一身虎膽。,為什麼我突然流淚了!,我要讓你 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
